name: 📋 Quality Checks

on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]

jobs:
  lint:
    name: 📋 Lint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v5

      - name: 📦 Install Mise
        run: |
          curl https://mise.run | sh
          mise install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧪 Lint
        run: mise lint

  test:
    name: 📋 Test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Git clone the repository
        uses: actions/checkout@v5

      - name: 📦 Install Mise
        run: |
          curl https://mise.run | sh
          mise install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🧪 Lint
        run: mise lint

      - name: 🧪 Test
        run: mise test
