name: ☁️ Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Code
        uses: actions/checkout@v5

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 📦 Install Mise
        run: |
          curl https://mise.run | sh
          mise install

      - name: ☁️ Release
        run: |
          mise release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
