name: 📋 Quality

on:
  pull_request:
    types: [ synchronize, opened, reopened, ready_for_review ]

concurrency:
  group: test-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4

      - name: Lint
        run: |
          go install github.com/mgechev/revive@latest
          make lint

      - name: Test
        run: |
          make test
